CC = g++
CFLAGS = -std=c++17 -Wall -Wextra -Wpedantic -Wformat -Wconversion -Werror # add -Wsecurity

SRC = main.cpp grafo.cpp cfc.cpp utils.cpp
HEADERS = grafo.hpp cfc.hpp utils.hpp

# Define OBJS as the object files corresponding to the source files
OBJS = $(SRC:.cpp=.o)

TARGET = tp1

# Build rules
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

%.o: %.cpp $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@

# Clean rule
clean:
	rm -f $(OBJS) $(TARGET)